/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.vcompany.teramusique.view.dialogs;

import com.vcompany.teramusique.controller.MusicoterapeutaController;
import com.vcompany.teramusique.controller.SessaoController;
import com.vcompany.teramusique.exceptions.SessaoException;
import com.vcompany.teramusique.model.Sessao;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class DlgCadSessao extends javax.swing.JDialog {

    /**
     * Creates new form DlgCadSessao
     */
    MusicoterapeutaController musicoterapeutaCont;
    SessaoController sCont;
    Sessao sessaoCorrente;

    public DlgCadSessao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        musicoterapeutaCont = new MusicoterapeutaController();
        sCont = new SessaoController();
        this.sessaoCorrente = new Sessao();
        this.habilitarCampos(false);
        this.limparCampos();

    }

    public void habilitarCampos(boolean flag) {
        for (int i = 0; i < abaFormulario.getComponents().length; i++) {
            abaFormulario.getComponent(i).setEnabled(flag);
        }
        btnAdicionarPaciente.setEnabled(flag);
        btnSelecionarMusicoterapeutaResp.setEnabled(flag);
        btnSelecionarMusicoterapeutas.setEnabled(flag);
        btnSelecionarMusica.setEnabled(flag);

        edtData.setEnabled(flag);
        edtHorario.setEnabled(flag);
        edtMusicoterapeutaResp.setEnabled(flag);
        edtInfoPreSessao.setEnabled(flag);
        edtInfoPosSessao.setEnabled(flag);

    }

    public void limparCampos() {
        edtData.setText("");
        edtHorario.setText("");
        edtMusicoterapeutaResp.setText("");
        edtInfoPreSessao.setText("");
        edtInfoPosSessao.setText("");

//        sCont.atualizarTabelaPacienteSessao(grdPacientesSelecionados, sessaoCorrente.getLstPacientes());

        //este comando serve para trocar de aba usando Jtabbedblabla. 
        tblpDados.setSelectedComponent(abaFormulario);
    }

    public void preencherFormulario(Sessao sessao) {
        edtData.setText(sessao.getData() + "");
        edtHorario.setText(sessao.getHorario());
        edtMusicoterapeutaResp.setText(sessao.getMusicoterapeutaResp().toString());

        sCont.atualizarTabelaMusicoterapeutasSessao(grdMusicoterapeutasSelecionados, sessao.getLstMusicoterapeutas());

        sCont.atualizarTabelaPacienteSessao(grdTodasAsSessoes, sessao.getLstPacientes());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        tblpDados = new javax.swing.JTabbedPane();
        abaFormulario = new javax.swing.JPanel();
        pnlDadosSessao = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtHorario = new javax.swing.JTextField();
        pnlPacientes = new javax.swing.JPanel();
        btnAdicionarPaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdPacientesSelecionados = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        pnlMusicoterapeuta = new javax.swing.JPanel();
        edtMusicoterapeutaResp = new javax.swing.JTextField();
        lblMusicoterapeutaResp = new javax.swing.JLabel();
        btnSelecionarMusicoterapeutaResp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSelecionarMusicoterapeutas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grdMusicoterapeutasSelecionados = new javax.swing.JTable();
        pnlInfoSessao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtInfoPreSessao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtInfoPosSessao = new javax.swing.JTextField();
        pnlMusicas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnSelecionarMusica = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        grdMusicasSelecionadas = new javax.swing.JTable();
        abaTodasAsSessoes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdTodasAsSessoes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblData.setText("Data");

        edtData.setText("jTextField2");

        jLabel3.setText("Horario");

        edtHorario.setText("jTextField1");

        javax.swing.GroupLayout pnlDadosSessaoLayout = new javax.swing.GroupLayout(pnlDadosSessao);
        pnlDadosSessao.setLayout(pnlDadosSessaoLayout);
        pnlDadosSessaoLayout.setHorizontalGroup(
            pnlDadosSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        pnlDadosSessaoLayout.setVerticalGroup(
            pnlDadosSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosSessaoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnlDadosSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdicionarPaciente.setText("Adicionar");

        grdPacientesSelecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(grdPacientesSelecionados);

        jLabel6.setText("Paciente(s)");

        javax.swing.GroupLayout pnlPacientesLayout = new javax.swing.GroupLayout(pnlPacientes);
        pnlPacientes.setLayout(pnlPacientesLayout);
        pnlPacientesLayout.setHorizontalGroup(
            pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(pnlPacientesLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarPaciente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPacientesLayout.setVerticalGroup(
            pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacientesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnAdicionarPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        edtMusicoterapeutaResp.setText("jTextField3");
        edtMusicoterapeutaResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMusicoterapeutaRespActionPerformed(evt);
            }
        });

        lblMusicoterapeutaResp.setText("Musicoterapeuta responsável");

        btnSelecionarMusicoterapeutaResp.setText("jButton1");
        btnSelecionarMusicoterapeutaResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarMusicoterapeutaRespActionPerformed(evt);
            }
        });

        jLabel4.setText("Musicoterapeutas incluídos");

        btnSelecionarMusicoterapeutas.setText("jButton1");
        btnSelecionarMusicoterapeutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarMusicoterapeutasActionPerformed(evt);
            }
        });

        grdMusicoterapeutasSelecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(grdMusicoterapeutasSelecionados);

        javax.swing.GroupLayout pnlMusicoterapeutaLayout = new javax.swing.GroupLayout(pnlMusicoterapeuta);
        pnlMusicoterapeuta.setLayout(pnlMusicoterapeutaLayout);
        pnlMusicoterapeutaLayout.setHorizontalGroup(
            pnlMusicoterapeutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusicoterapeutaLayout.createSequentialGroup()
                .addGroup(pnlMusicoterapeutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMusicoterapeutaLayout.createSequentialGroup()
                        .addComponent(edtMusicoterapeutaResp, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSelecionarMusicoterapeutaResp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMusicoterapeutaResp)
                    .addGroup(pnlMusicoterapeutaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionarMusicoterapeutas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMusicoterapeutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMusicoterapeutaLayout.setVerticalGroup(
            pnlMusicoterapeutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusicoterapeutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMusicoterapeutaResp)
                .addGap(3, 3, 3)
                .addGroup(pnlMusicoterapeutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtMusicoterapeutaResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarMusicoterapeutaResp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMusicoterapeutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMusicoterapeutaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSelecionarMusicoterapeutas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Informações da sessão");

        edtInfoPreSessao.setText("jTextField1");

        jLabel2.setText("Informações pós sessão (Atualize depois da sessão)");

        edtInfoPosSessao.setText("jTextField1");

        javax.swing.GroupLayout pnlInfoSessaoLayout = new javax.swing.GroupLayout(pnlInfoSessao);
        pnlInfoSessao.setLayout(pnlInfoSessaoLayout);
        pnlInfoSessaoLayout.setHorizontalGroup(
            pnlInfoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtInfoPreSessao)
                    .addGroup(pnlInfoSessaoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlInfoSessaoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlInfoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoSessaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(edtInfoPosSessao)
                    .addContainerGap()))
        );
        pnlInfoSessaoLayout.setVerticalGroup(
            pnlInfoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtInfoPreSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(pnlInfoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoSessaoLayout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(edtInfoPosSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel5.setText("Selecione pelo menos uma música para conduzir a sessão");

        btnSelecionarMusica.setText("jButton1");
        btnSelecionarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarMusicaActionPerformed(evt);
            }
        });

        grdMusicasSelecionadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(grdMusicasSelecionadas);

        javax.swing.GroupLayout pnlMusicasLayout = new javax.swing.GroupLayout(pnlMusicas);
        pnlMusicas.setLayout(pnlMusicasLayout);
        pnlMusicasLayout.setHorizontalGroup(
            pnlMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusicasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlMusicasLayout.setVerticalGroup(
            pnlMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusicasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarMusica))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaFormularioLayout = new javax.swing.GroupLayout(abaFormulario);
        abaFormulario.setLayout(abaFormularioLayout);
        abaFormularioLayout.setHorizontalGroup(
            abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaFormularioLayout.createSequentialGroup()
                .addGroup(abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaFormularioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaFormularioLayout.createSequentialGroup()
                                .addComponent(pnlMusicoterapeuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addComponent(pnlDadosSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaFormularioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfoSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        abaFormularioLayout.setVerticalGroup(
            abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaFormularioLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaFormularioLayout.createSequentialGroup()
                        .addComponent(pnlDadosSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(pnlMusicoterapeuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblpDados.addTab("Formulário", abaFormulario);

        grdTodasAsSessoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(grdTodasAsSessoes);

        javax.swing.GroupLayout abaTodasAsSessoesLayout = new javax.swing.GroupLayout(abaTodasAsSessoes);
        abaTodasAsSessoes.setLayout(abaTodasAsSessoesLayout);
        abaTodasAsSessoesLayout.setHorizontalGroup(
            abaTodasAsSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        abaTodasAsSessoesLayout.setVerticalGroup(
            abaTodasAsSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTodasAsSessoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblpDados.addTab("Todas as sessões", abaTodasAsSessoes);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tblpDados, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblpDados, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {

            Sessao s = new Sessao(edtData.getText(), edtHorario.getText(), edtInfoPreSessao.getText(), edtInfoPosSessao.getText(),
                    sessaoCorrente.getMusicoterapeutaResp(),
                    sessaoCorrente.getLstMusicoterapeutas(),
                    sessaoCorrente.getLstMusicas(),
                    sessaoCorrente.getLstPacientes());

            sCont.cadastrarSessao(s);

            dispose();

            sCont.atualizarTabela(grdMusicoterapeutasSelecionados);
            sCont.atualizarTabela(grdPacientesSelecionados);

            this.habilitarCampos(false);
            this.limparCampos();

        } catch (SessaoException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarCampos(true);
        this.limparCampos();
        sessaoCorrente = new Sessao();
        tblpDados.setSelectedComponent(abaFormulario);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        sessaoCorrente = new Sessao();

        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        Sessao sessaoExcluida = (Sessao) this.getObjetoSelecionadoNaGrid();

        if (sessaoExcluida == null)
            JOptionPane.showMessageDialog(this, "Primeiro, selecione um registro na tabela. ");
        else {
            int response = JOptionPane.showConfirmDialog(null,
                    "Deseja excluir a Sessao \n( "
                    + sessaoExcluida.getId() + " ), de Musicoterapeuta responsàvel: "
                    + sessaoExcluida.getMusicoterapeutaResp().toString() + "?",
                    "Confirmar exclusão",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                try {
                    sCont.excluirSessao(sessaoCorrente);
                    sCont.atualizarTabela(grdTodasAsSessoes);
                    JOptionPane.showMessageDialog(this, "Exlusão feita com sucesso!");
                } catch (SessaoException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        sessaoCorrente = (Sessao) this.getObjetoSelecionadoNaGrid();

        if (sessaoCorrente == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            this.limparCampos();
            this.habilitarCampos(true);
            this.preencherFormulario(sessaoCorrente);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSelecionarMusicoterapeutaRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarMusicoterapeutaRespActionPerformed
        // TODO add your handling code here:
        DlgSelecaoMusicoterapeutaParaSessao telaMusicoterapeuta = new DlgSelecaoMusicoterapeutaParaSessao(new Frame(), true, sessaoCorrente);
        telaMusicoterapeuta.setVisible(true);
        
        edtMusicoterapeutaResp.setText(sessaoCorrente.getMusicoterapeutaResp().toStringNome());
    }//GEN-LAST:event_btnSelecionarMusicoterapeutaRespActionPerformed

    private void btnSelecionarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarMusicaActionPerformed
        // TODO add your handling code here:
        DlgSelecaoMusicaParaSessao telaMusica = new DlgSelecaoMusicaParaSessao(new Frame(), true, sessaoCorrente);
        telaMusica.setVisible(true);
    }//GEN-LAST:event_btnSelecionarMusicaActionPerformed

    private void btnSelecionarMusicoterapeutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarMusicoterapeutasActionPerformed
        // TODO add your handling code here:
        DlgSelecaoMusicoterapeutaParaSessao telaMusicoterapeutas = new DlgSelecaoMusicoterapeutaParaSessao(new Frame(), true, sessaoCorrente);
        telaMusicoterapeutas.setVisible(true);
        
        sCont.atualizarTabelaMusicoterapeutasSessao(grdMusicoterapeutasSelecionados, sessaoCorrente.getLstMusicoterapeutas());
    }//GEN-LAST:event_btnSelecionarMusicoterapeutasActionPerformed

    private void edtMusicoterapeutaRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMusicoterapeutaRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMusicoterapeutaRespActionPerformed

    private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdTodasAsSessoes.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdTodasAsSessoes.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaFormulario;
    private javax.swing.JPanel abaTodasAsSessoes;
    private javax.swing.JButton btnAdicionarPaciente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionarMusica;
    private javax.swing.JButton btnSelecionarMusicoterapeutaResp;
    private javax.swing.JButton btnSelecionarMusicoterapeutas;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtHorario;
    private javax.swing.JTextField edtInfoPosSessao;
    private javax.swing.JTextField edtInfoPreSessao;
    private javax.swing.JTextField edtMusicoterapeutaResp;
    private javax.swing.JTable grdMusicasSelecionadas;
    private javax.swing.JTable grdMusicoterapeutasSelecionados;
    private javax.swing.JTable grdPacientesSelecionados;
    private javax.swing.JTable grdTodasAsSessoes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMusicoterapeutaResp;
    private javax.swing.JPanel pnlDadosSessao;
    private javax.swing.JPanel pnlInfoSessao;
    private javax.swing.JPanel pnlMusicas;
    private javax.swing.JPanel pnlMusicoterapeuta;
    private javax.swing.JPanel pnlPacientes;
    private javax.swing.JTabbedPane tblpDados;
    // End of variables declaration//GEN-END:variables
}
