/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.vcompany.teramusique.view.dialogs;

import com.vcompany.teramusique.controller.MusicaController;
import com.vcompany.teramusique.controller.MusicoterapeutaController;
import com.vcompany.teramusique.exceptions.MusicaException;
import com.vcompany.teramusique.model.Musica;
import com.vcompany.teramusique.model.Sessao;
import javax.swing.JOptionPane;
import org.hibernate.engine.transaction.jta.platform.internal.JOTMJtaPlatform;

/**
 *
 * @author vitor
 */
public class DlgSelecaoMusicaParaSessao extends javax.swing.JDialog {

    /**
     * Creates new form DlgSelecaoMusicaParaSessao
     */
    Sessao sessao;
    Musica musicaEscolhida;
    MusicaController mCont;

    public DlgSelecaoMusicaParaSessao(java.awt.Frame parent, boolean modal, Sessao sessao) {

        super(parent, modal);
        initComponents();

        this.mCont = new MusicaController();
        this.musicaEscolhida = new Musica();
        this.sessao = sessao;

        this.mCont.atualizarTabela(grdMusicas);

        this.habilitarCampos(false);
        this.limparCampos();

    }

    public void habilitarCampos(boolean flag) {
        for (int i = 0; i < abaMusicas.getComponents().length; i++) {
            abaMusicas.getComponent(i).setEnabled(flag);
        }
        btnNovo.setEnabled(flag);
        btnEditar.setEnabled(flag);
        btnExcluir.setEnabled(flag);
        btnCancelar.setEnabled(flag);

        edtTitulo.setEnabled(false);
        edtDuracao.setEnabled(false);
        edtAlbum.setEnabled(false);
        edtArtista.setEnabled(false);
        edtGenero.setEnabled(false);
        edtFinalidadeNaSessao.setEnabled(false);

    }

    public void limparCampos() {
        edtTitulo.setText("");
        edtArtista.setText("");
        edtDuracao.setText("");
        edtGenero.setText("");
        edtAlbum.setText("");
        edtFinalidadeNaSessao.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPnlMusicas = new javax.swing.JTabbedPane();
        abaMusicas = new javax.swing.JPanel();
        pnlBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtArtista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtAlbum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtGenero = new javax.swing.JTextField();
        edtDuracao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtFinalidadeNaSessao = new javax.swing.JTextField();
        abaTodasAsMusicas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdMusicas = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnExcluir);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnSalvar);

        jLabel1.setText("TItulo");

        edtTitulo.setText("jTextField1");

        jLabel2.setText("Artista");

        edtArtista.setText("jTextField1");

        jLabel3.setText("Álbum");

        edtAlbum.setText("jTextField1");

        jLabel4.setText("Gênero");

        edtGenero.setText("jTextField1");

        edtDuracao.setText("jTextField1");

        jLabel5.setText("Duração");

        jLabel6.setText("Qual a finalidade da música na sessão");

        edtFinalidadeNaSessao.setText("jTextField1");

        javax.swing.GroupLayout abaMusicasLayout = new javax.swing.GroupLayout(abaMusicas);
        abaMusicas.setLayout(abaMusicasLayout);
        abaMusicasLayout.setHorizontalGroup(
            abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaMusicasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtFinalidadeNaSessao)
                    .addComponent(jLabel2)
                    .addGroup(abaMusicasLayout.createSequentialGroup()
                        .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(edtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edtArtista, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edtGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(edtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaMusicasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        abaMusicasLayout.setVerticalGroup(
            abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaMusicasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(abaMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaMusicasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaMusicasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtFinalidadeNaSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tbdPnlMusicas.addTab("Adicionar Musica", abaMusicas);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        grdMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdMusicas);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaTodasAsMusicasLayout = new javax.swing.GroupLayout(abaTodasAsMusicas);
        abaTodasAsMusicas.setLayout(abaTodasAsMusicasLayout);
        abaTodasAsMusicasLayout.setHorizontalGroup(
            abaTodasAsMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTodasAsMusicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(abaTodasAsMusicasLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btnAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaTodasAsMusicasLayout.setVerticalGroup(
            abaTodasAsMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTodasAsMusicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar)
                .addContainerGap())
        );

        tbdPnlMusicas.addTab("Selecionar musica", abaTodasAsMusicas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbdPnlMusicas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbdPnlMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarCampos(true);
        this.limparCampos();

    }//GEN-LAST:event_btnNovoActionPerformed

    public void preencherFormulario(Musica m) {
        edtTitulo.setText(m.getTitulo());
        edtArtista.setText(m.getArtista() + "");
        edtAlbum.setText(m.getAlbum() + "");
        edtGenero.setText(m.getGenero());
        edtDuracao.setText(m.getDuracao() + "");
        edtFinalidadeNaSessao.setText(m.getFinalidadeNaSessao() + "");
    }

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        if (musicaEscolhida == null) {
            int response = JOptionPane.showConfirmDialog(null,
                    "Nenhum item foi escolhido. Deseja continuar?",
                    "Confirm",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                tbdPnlMusicas.setSelectedIndex(0);
            } else {
                if (sessao.getLstMusicas().contains(musicaEscolhida)) {
                    JOptionPane.showMessageDialog(null, "Esta musica já será reproduzida na sessão.");
                } else {
                    this.sessao.getLstMusicas().add(musicaEscolhida);
                    tbdPnlMusicas.setSelectedIndex(0);

                }
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {

            Musica novaMusica = new Musica(edtTitulo.getText(), edtArtista.getText(), edtAlbum.getText(), edtGenero.getText(), edtDuracao.getText(), edtFinalidadeNaSessao.getText());
            mCont.cadastrarMusica(novaMusica);
            
            

            this.habilitarCampos(true);
            this.limparCampos();
        } catch (MusicaException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        tbdPnlMusicas.setSelectedIndex(1);
        Musica musicaExcluida = (Musica) this.getObjetoSelecionadoNaGrid();

        if (musicaExcluida == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {

            int response = JOptionPane.showConfirmDialog(null,
                    "Deseja exlcuir o musica  \n("
                    + musicaExcluida.getTitulo() + ", de: "
                    + musicaExcluida.getArtista()+ ") ?",
                    "Confirmar exclusão",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                        tbdPnlMusicas.setSelectedIndex(1);
                try {
                    mCont.excluirMusica(musicaExcluida);

                    mCont.atualizarTabela(grdMusicas);
                    JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
                } catch (MusicaException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Musica musicaEditando = (Musica) this.getObjetoSelecionadoNaGrid();

        if (musicaEditando == null)
            JOptionPane.showMessageDialog(this, "Primeiro, selecione uma musica na tabela.");
        else {
            this.limparCampos();
            this.habilitarCampos(true);
            this.preencherFormulario(musicaEditando);
        }
             
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void grdMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdMusicasMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            btnEditarActionPerformed(null);
        }
    }//GEN-LAST:event_grdMusicasMouseClicked

    private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdMusicas.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdMusicas.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaMusicas;
    private javax.swing.JPanel abaTodasAsMusicas;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtAlbum;
    private javax.swing.JTextField edtArtista;
    private javax.swing.JTextField edtDuracao;
    private javax.swing.JTextField edtFinalidadeNaSessao;
    private javax.swing.JTextField edtGenero;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JTable grdMusicas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JTabbedPane tbdPnlMusicas;
    // End of variables declaration//GEN-END:variables
}
