/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.vcompany.teramusique.view.dialogs;

import com.vcompany.teramusique.controller.MusicoterapeutaController;
import com.vcompany.teramusique.model.Musicoterapeuta;
import com.vcompany.teramusique.model.Sessao;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author vitor
 */
public class DlgSelecaoMusicoterapeutaRespParaSessao extends javax.swing.JDialog {

    /**
     * Creates new form DlgSelecaoMusicoterapeutasParaSessao
     */
    MusicoterapeutaController mCont;
    Sessao sessaoSendoCadastrada;
    Musicoterapeuta musicoterapeutaEscolhido;

    public DlgSelecaoMusicoterapeutaRespParaSessao(java.awt.Frame parent, boolean modal, Sessao sessao) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        mCont = new MusicoterapeutaController();
        this.musicoterapeutaEscolhido = new Musicoterapeuta();
        this.sessaoSendoCadastrada = sessao;

        mCont.atualizarTabela(grdMusicoterapeutasDisponiveis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtFiltrarNome = new javax.swing.JTextField();
        grdMusicoterapeutasDisp = new javax.swing.JScrollPane();
        grdMusicoterapeutasDisponiveis = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMusicoterapeutasSelecionados = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jSplitPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecionar musicoterapeuta para sessão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 1, 18))); // NOI18N

        jLabel1.setText("Filtrar (Nome) : ");

        edtFiltrarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtFiltrarNomeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtFiltrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFiltrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        grdMusicoterapeutasDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdMusicoterapeutasDispMouseClicked(evt);
            }
        });

        grdMusicoterapeutasDisponiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdMusicoterapeutasDisponiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdMusicoterapeutasDisponiveisMouseClicked(evt);
            }
        });
        grdMusicoterapeutasDisp.setViewportView(grdMusicoterapeutasDisponiveis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grdMusicoterapeutasDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grdMusicoterapeutasDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        txtMusicoterapeutasSelecionados.setColumns(20);
        txtMusicoterapeutasSelecionados.setRows(5);
        jScrollPane2.setViewportView(txtMusicoterapeutasSelecionados);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grdMusicoterapeutasDispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdMusicoterapeutasDispMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grdMusicoterapeutasDispMouseClicked

    private void grdMusicoterapeutasDisponiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdMusicoterapeutasDisponiveisMouseClicked
        // TODO add your handling code here:
        musicoterapeutaEscolhido = (Musicoterapeuta) this.getObjetoSelecionadoNaGrid();

        if (musicoterapeutaEscolhido == null) {
            JOptionPane.showMessageDialog(this, "Pirmeiro, selecione um registro na tabela.");
        } else {
            txtMusicoterapeutasSelecionados.setText(musicoterapeutaEscolhido.toString());
        }

    }//GEN-LAST:event_grdMusicoterapeutasDisponiveisMouseClicked

    private void edtFiltrarNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtFiltrarNomeKeyPressed
        // TODO add your handling code here:
        String nomeDigitado = edtFiltrarNome.getText();
        if (!nomeDigitado.isEmpty())
            this.mCont.atualizarTabela(grdMusicoterapeutasDisponiveis, nomeDigitado);
        else
            this.mCont.atualizarTabela(grdMusicoterapeutasDisponiveis);
    }//GEN-LAST:event_edtFiltrarNomeKeyPressed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        musicoterapeutaEscolhido = (Musicoterapeuta) this.getObjetoSelecionadoNaGrid();

        if (musicoterapeutaEscolhido == null) {
            int response = JOptionPane.showConfirmDialog(null,
                    "Nenhum item foi escolhido. Deseja continuar?",
                    "Confirm",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.OK_OPTION) {
                dispose();
            }
        } else {
            if (sessaoSendoCadastrada.getMusicoterapeutaResp().equals(musicoterapeutaEscolhido)) {
                JOptionPane.showMessageDialog(null, "Este musicoterapeuta já está cadastrado.");
            } else if (sessaoSendoCadastrada.getLstMusicoterapeutas() == null) {
                JOptionPane.showMessageDialog(null, "Lista de musicoterapeutas vazia.");
            } else {
                this.sessaoSendoCadastrada.setMusicoterapeutaResp(musicoterapeutaEscolhido);
                dispose();

            }
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JTextField edtFiltrarNome;
    private javax.swing.JScrollPane grdMusicoterapeutasDisp;
    private javax.swing.JTable grdMusicoterapeutasDisponiveis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea txtMusicoterapeutasSelecionados;
    // End of variables declaration//GEN-END:variables

    private Object getObjetoSelecionadoNaGrid() {
        int rowClicked = grdMusicoterapeutasDisponiveis.getSelectedRow();
        Object obj = null;
        if (rowClicked >= 0) {
            obj = grdMusicoterapeutasDisponiveis.getModel().getValueAt(rowClicked, -1);
        }
        return obj;
    }
}
